version: "3.9"

services:
  shortli-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
      args:
        - INFISICAL_TOKEN=${INFISICAL_TOKEN}
        - ENV=dev
        - PROJECT_ID=6e57cafb-8fbb-4044-951a-0d517cf651a2
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - shortli_redis:/data

volumes:
  shortli_redis:
    driver: local
