version: "3.9"

services:
  shortli-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
      args:
        - INFISICAL_TOKEN=${INFISICAL_TOKEN}
        - ENV=prod
        - PROJECT_ID=6e57cafb-8fbb-4044-951a-0d517cf651a2
    restart: always
    expose:
      - "6379"
    volumes:
      - shortli_redis:/data
    networks:
      sli-network:
        ipv4_address: 172.20.0.11

  shortli-app:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - INFISICAL_TOKEN=${INFISICAL_TOKEN}
        - PROJECT_ID=6e57cafb-8fbb-4044-951a-0d517cf651a2
    image: shortli-app:shortli
    restart: always
    depends_on:
      shortli-redis:
        condition: service_healthy
    links:
      - "shortli-redis:172.20.0.11"
    ports:
      - "3131:3000"
    networks:
      sli-network:
        ipv4_address: 172.20.0.10

volumes:
  shortli_redis:
    driver: local

networks:
  sli-network:
    driver: bridge
    name: sli-network
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
