version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redisDeveloperPW
    volumes: 
      - redis:/data
      
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=D3V_PW
      - POSTGRES_USER=dev
      - POSTGRES_DB=shortli_db
      
volumes:
  redis:
    driver: local
    
  postgres:
    driver: local