import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";

import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased min-h-screen`}>
        <div className='max-w-[2560px] mx-auto'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
